env:
  global:
    - TERM=dumb
notifications:
  email: false
git:
  quiet: true
  depth: false
language: java
jdk: openjdk11
node_js: lts/*
python: 3.7
os: linux
addons:
  apt:
    update: true
    packages:
      - curl
      - python3-pip
install: true
before_install:
  - export DISPLAY=:99.0
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master ;
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
    fi
    source ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
  - stop_any 80 8001 8002 8080 5432
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user --upgrade pip setuptools
  - pip install --user --upgrade httpie
jobs:
  include:
    - stage: test
      name: annotation
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw -f annotation
        - bash $TRAVIS_BUILD_DIR/annotation/annotation-application/target/*.jar &
        - wait_for 8080
        - http :8080/hello/max
        - http :8080/actuator/info
        - http :8080/ololo-trololo
        - stop_any 80
    - stage: test
      name: spring.factories
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw -f spring.factories
        - bash $TRAVIS_BUILD_DIR/spring.factories/spring.factories-application/target/*.jar &
        - wait_for 8080
        - http :8080/hello/max
        - http :8080/actuator/info
        - http :8080/ololo-trololo
        - stop_any 80
cache:
  pip: true
  packages: true
  directories:
    - ~/.local
    - ~/.gradle
    - ~/.m2
